var aifFunctions = {}

aifFunctions.updateAccoutsTableRowOnPriceChange = directEquityFunctions.updateAccoutsTableRowOnPriceChange

aifFunctions.updateContainerCurrentUnbookedValue = directEquityFunctions.updateContainerCurrentUnbookedValue

aifFunctions.calculateContainerOpenPosBackExtrapolation = directEquityFunctions.calculateContainerOpenPosBackExtrapolation

aifFunctions.setContainerOpenPosRow = directEquityFunctions.setContainerOpenPosRow

aifFunctions.setContainerClosePosRow = directEquityFunctions.setContainerClosePosRow

aifFunctions.containerAccountsRowProcessTransactionForm = pmsFunctions.containerAccountsRowProcessTransactionForm

aifFunctions.containerAccountsRowAddTransactionForm = pmsFunctions.containerAccountsRowAddTransactionForm

aifFunctions.displayTransactionFields = pmsFunctions.displayTransactionFields

aifFunctions.validateTransactionForm = pmsFunctions.validateTransactionForm

aifFunctions

containerTypeFunctions[2] = aifFunctions